config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"
  get 'home/top' => 'homes#top'
  get 'home/about' => 'home#about', as: 'about'

  devise_for :users
  resources :application, only: [:new, :update]
  resources :users, only: [:new, :index, :show, :edit, :update]
  resources :books, only: [:create, :index, :show, :edit, :destroy, :update]
  # For details on the DSL




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true,  length: {minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to "/books"
  end

  def edit
    is_matching_login_user
    @book = Book.find(params[:id])
  end

  def update
    is_matching_login_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

   def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @book = Book.new
    @users = User.all
  end

  def edit
     is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if book.errors.any? %>
  <h1>
    <%= book.errors.count %>errors prohibited this obj from being saved:
  </h1>
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

    <div class="col-md-3">
   <h1>User info</h1>
   <%= image_tag current_user.get_profile_image(100,100) %>
 <table class="table table">
   <tbody>
   <tr>
 <th>name</th>
   <th><%= current_user.name %></th>
   </tr>
   <tr>
 <th>introduction</th>
   <th><%= current_user.introduction %></th>
   </tr>
   </tbody>
 </table>
  <div class="row">
    <%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<h1>New book</h1>
<%= form_with model: book do |f| %>
  <p>Title</p>
    <%= f.text_field :title, style: "width:100%" %>
  <p>Opinion</p>
    <%= f.text_area :body, style: "width:100%" %>
  <p><%= f.submit 'Create Book', class: "btn btn-success" %></p>
<% end %>
 </div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <h1>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
  </h1>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit "Update Book" %>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'list', book: @book %>

    <div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class = "table table-hover">
<thead>
<tr>
    <th>Title</th>
    <th>Opinion</th>
</tr>
</thead>

<tbody>
<% @books.each do |book| %>

<tr>
 <td>
  <%= link_to user_path(book.user.id) do %>
   <%= image_tag book.user.get_profile_image(100,100) %>
  <% end %>
 </td>
 <td>
  <%= link_to book_path(book.id) do %>
   <%= book.title %>
  <% end %>
 </td>

 <td><%= book.body %></td>
</tr>
<% end %>
</tbody>
</table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
   <h1>User info</h1>
   <%= image_tag @user.get_profile_image(100,100) %>
 <table class="table table">
   <tbody>
   <tr>
 <th>name</th>
   <th><%= @user.name %></th>
   </tr>
   <tr>
 <th>introduction</th>
   <th><%= @user.introduction %></th>
   </tr>
   </tbody>
 </table>

<div class="row">
    <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<h1>New book</h1>
<%= form_with model: @books do |f| %>
  <p>Title</p>
    <%= f.text_field :title, style: "width:100%" %>
  <p>Opinion</p>
    <%= f.text_area :body, style: "width:100%" %>
  <p><%= f.submit 'Create Book', class: "btn btn-success" %></p>
<% end %>
    </div>

    <div class="col-md-8 offset-md-1">
<h1>Book detail</h1>
<table class= "table talble">
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@book.user.id) do %>
        <%= image_tag @book.user.get_profile_image(100,100) %>
        <%= @book.user.name %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(@book.id) do %>
          <%= @book.title %>
        <% end %>
      </td>
      <td>
        <%= @book.body %>
        <% if @book.user == current_user %>
        <%= link_to "Edit", edit_book_path(@book.id) %>
        <%= link_to "Destroy", book_path(@book), method: :delete %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
</div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
<h1>
  welcome to
  <i class="fas fa-book"></i>
  Bookers !!
</h1>
</div>

app/views/home/top.html.erb
<%= flash[:notice] %>
<div class="container">
<h1>
  welcome to
  <i class="fas fa-book"></i>
  Bookers !!
</h1>
<p>
  In
  <i class="fas fa-book"></i>
  Bookers,
</p>
<p>
  you can share and exchange your opinions, inpressions,
  and emotions
</p>
<p>
  about various books
</p>

<p><%= link_to "Log in", new_user_session_path %></p>
<p><%= link_to "Sign up", new_user_registration_path %></p>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>

<h1>welcome to Bookers !!</h1>
<p>
  In Bookers,
</p>
<p>
  you can share and exchange your opinions, inpressions,
  and emotions
</p>
<p>
  about various books
</p>

<p><%= link_to "Log in", new_user_session_path %></p>
<p><%= link_to "Sign up", new_user_registration_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/5c01a8143c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse-show" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                 <li class="nav-item">
                    <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                     <i class="fas fa-home"></i>
                     Home
                    <% end %>
                 </li>
                 <li class="nav-item">
                  <%= link_to "/users", class:"nav-link text-light" do %>
                     <i class="fas fa-users"></i>
                     Users
                    <% end %>
                 </li>
                 <li class="nav-item">
                   <%= link_to "/books", class:"nav-link text-light"  do %>
                  <i class="fas fa-book-open"></i>
                  Books
                  <% end %>
                </li>
                 <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i>
                  Log out
                  <% end %>
                </li>
              <% else %>
                 <li class="nav-item">
                  <%= link_to root_path, class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                  <% end %>
                </li>
                 <li class="nav-item">
                  <%= link_to about_path, class:"nav-link text-light" do %>
                  <i class="fas fa-link"></i>
                  About
                  <% end %>
                </li>
                 <li class="nav-item">
                  <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i>
                  Sign up
                  <% end %>
                </li>
                 <li class="nav-item">
                  <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                  <% end %>
                </li>
              <% end %>
             </ul>
          </div>
        </div>
      </nav>
    </header>
<main class="mb-auto">
<%= yield %>
</main>
   <footer>
    <div class="container mt-5">
     <div class="row">
      <div class="mx-auto">
      <p>CopyRight Infratop.inc</p>
      </div>
     </div>
    </div>
   </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <h1>
    <%= @user.errors.count %>errors prohibited this obj from being saved:
  </h1>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
<h1>Users info</h1>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder:"プロフィール画像",accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
  <%= f.submit "Update User" %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'books/list', book: @book %>

  <div class="col-md-8 offset-md-1">
<h1>Users</h1>
<table class= "table table">
<thead>
<tr>
    <th>image</th>
    <th>name</th>
    <th></th>
</tr>
</thead>

<tbody>
<% @users.each do |user| %>

<tr>
 <td><%= image_tag user.get_profile_image(100,100) %></td>
 <td><%= user.name %></td>
 <td><%= link_to "Show", user_path(user.id) %></td>
<% end %>
</tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<% if @book.errors.any? %>
  <h1>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
  </h1>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
   <h1>User info</h1>
   <%= image_tag @user.get_profile_image(100,100) %>
 <table class="table table">
   <tbody>
   <tr>
 <th>name</th>
   <th><%= @user.name %></th>
   </tr>
   <tr>
 <th>introduction</th>
   <th><%= @user.introduction %></th>
   </tr>
   </tbody>
 </table>

<div class="row">
    <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <p>Title</p>
    <%= f.text_field :title, style: "width:100%" %>
  <p>Opinion</p>
    <%= f.text_area :body, style: "width:100%" %>
  <p><%= f.submit 'Create Book', class: "btn btn-success" %></p>
<% end %>
  </div>

  <div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table">
<thead>
<tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
</tr>
</thead>

<tbody>
<% @books.each do |book| %>

<tr>
 <td>
   <%= link_to user_path(@user.id) do %>
   <%= image_tag book.user.get_profile_image(100,100) %>
   <% end %>
 </td>
 <td>
  <%= link_to book_path(book.id) do %>
   <%= book.title %>
  <% end %>
 </td>

 <td><%= book.body %></td>
</tr>
<% end %>
</tbody>
</table>
    </div>
  </div>
</div>